// <auto-generated />
using System;
using ControleHoras.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleHoras.Migrations
{
    [DbContext(typeof(EntityFactory))]
    [Migration("20220220195546_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleHoras.Model.Dia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraDois")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraQuatro")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraTres")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraUm")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Intervalo")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TotalHoras")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
